### Teste POST Assets
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Amazon",
    "symbol": "AMZN",
    "price": 73.50,
    "image": "/AMZN.png"
}

### Teste POST Assets
# @name createAsset2
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Google",
    "symbol": "GOOGL",
    "price": 68.90,
    "image": "/GOOGL.png"
}

### Teste POST Assets
# @name createAsset3
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "NVIDIA",
    "symbol": "NVDA",
    "price": 71.20,
    "image": "/NVDA.png"
}

### Teste GET Assets
GET http://localhost:3000/assets

### Teste GET Assets by Symbol
GET http://localhost:3000/assets/AMZN01

### Teste POST Wallets
# @name createWallet
POST http://localhost:3000/wallets
Content-Type: application/json

{
}

### Teste POST Wallets
# @name createWallet2
POST http://localhost:3000/wallets
Content-Type: application/json

{
}

### Teste GET Wallets
GET http://localhost:3000/wallets

### Teste GET Wallets by Id

@walletId = {{ createWallet.response.body._id }}
@walletId2 = {{ createWallet2.response.body._id }}
@assetId = {{ createAsset.response.body._id }}


GET http://localhost:3000/wallets/{{walletId}}

### Teste POST WalletAsset
# @name createWalletAsset
POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "asset": "{{assetId}}",
    "shares": 100
}

###
POST http://localhost:3000/assets/AMZN/dailies
Content-Type: application/json

{
  "date": "2024-10-10",
  "price": 95
}

###
GET http://localhost:3000/assets/AMZN/dailies

### Teste POST Order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "shares": 25,
    "partial": 0,
    "price": 71.50,
    "wallet": "{{walletId}}",
    "asset": "{{assetId}}",
    "type": "SELL"
}

### Teste POST Order
POST http://localhost:3000/orders
Content-Type: application/json

{
    "shares": 25,
    "partial": 0,
    "price": 71.50,
    "wallet": "{{walletId2}}",
    "asset": "{{assetId}}",
    "type": "BUY"
}


### Teste GET Order
GET http://localhost:3000/orders?walletId={{walletId}}