import Navbar from "@/my-app/components/csr/navbar/navbar";
import { ThemeProvider } from "@/my-app/context/theme-context";
import type { Metadata } from "next";
import "./globals.css";
import { MyWalletProvider } from "@/my-app/context/wallet-context";
import { ToastContainer } from "@/my-app/components/csr/toast/toast-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`h-screen flex flex-col antialiased`}
      >
        <ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
          <ToastContainer />
          <Navbar />
          <MyWalletProvider>
            <main className="container my-4 mx-auto px-4 flex flex-grow">
              {children}
            </main>
          </MyWalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
